/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.46
 * Generated at: 2020-02-07 11:49:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1546424098679L));
    _jspx_dependants.put("jar:file:/C:/Users/nicol/OneDrive/Desktop/workspaces/default-webapp/apache-tomcat-8.5.46/wtpwebapps/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ResourceBundle");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ResourceBundle resourceBundle = ResourceBundle.getBundle("jspProperties");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>");
      out.print(resourceBundle.getString("index.titolo"));
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome Icons -->\r\n");
      out.write("<link href=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin CSS -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/vendor/magnific-popup/magnific-popup.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme CSS - Includes Bootstrap -->\r\n");
      out.write("<link href=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/creative.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light fixed-top py-3\"\r\n");
      out.write("\t\tid=\"mainNav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">Start\r\n");
      out.write("\t\t\t\tBootstrap</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto my-2 my-lg-0\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">About</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#services\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#portfolio\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Masthead -->\r\n");
      out.write("\t<header class=\"masthead\">\r\n");
      out.write("\t\t<div class=\"container h-100\">\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"row h-100 align-items-center justify-content-center text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-10 align-self-end\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"text-uppercase text-white font-weight-bold\">Your\r\n");
      out.write("\t\t\t\t\t\tFavorite Source of Free Bootstrap Themes</h1>\r\n");
      out.write("\t\t\t\t\t<hr class=\"divider my-4\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 align-self-baseline\">\r\n");
      out.write("\t\t\t\t\t<p class=\"text-white-75 font-weight-light mb-5\">Start Bootstrap\r\n");
      out.write("\t\t\t\t\t\tcan help you build better websites using the Bootstrap framework!\r\n");
      out.write("\t\t\t\t\t\tJust download a theme and start customizing, no strings attached!</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary btn-xl js-scroll-trigger\" href=\"#about\">Find\r\n");
      out.write("\t\t\t\t\t\tOut More</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- About Section -->\r\n");
      out.write("\t<section class=\"page-section bg-primary\" id=\"about\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"text-white mt-0\">We've got what you need!</h2>\r\n");
      out.write("\t\t\t\t\t<hr class=\"divider light my-4\">\r\n");
      out.write("\t\t\t\t\t<p class=\"text-white-50 mb-4\">Start Bootstrap has everything\r\n");
      out.write("\t\t\t\t\t\tyou need to get your new website up and running in no time! Choose\r\n");
      out.write("\t\t\t\t\t\tone of our open source, free to download, and easy to use themes!\r\n");
      out.write("\t\t\t\t\t\tNo strings attached!</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-light btn-xl js-scroll-trigger\" href=\"#services\">Get\r\n");
      out.write("\t\t\t\t\t\tStarted!</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Services Section -->\r\n");
      out.write("\t<section class=\"page-section\" id=\"services\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2 class=\"text-center mt-0\">At Your Service</h2>\r\n");
      out.write("\t\t\t<hr class=\"divider my-4\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-4x fa-gem text-primary mb-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"h4 mb-2\">Sturdy Themes</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted mb-0\">Our themes are updated regularly to\r\n");
      out.write("\t\t\t\t\t\t\tkeep them bug free!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-4x fa-laptop-code text-primary mb-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"h4 mb-2\">Up to Date</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted mb-0\">All dependencies are kept current\r\n");
      out.write("\t\t\t\t\t\t\tto keep things fresh.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-4x fa-globe text-primary mb-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"h4 mb-2\">Ready to Publish</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted mb-0\">You can use this design as is, or\r\n");
      out.write("\t\t\t\t\t\t\tyou can make changes!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-4x fa-heart text-primary mb-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"h4 mb-2\">Made with Love</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted mb-0\">Is it really open source if it's\r\n");
      out.write("\t\t\t\t\t\t\tnot made with love?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Portfolio Section -->\r\n");
      out.write("\t<section id=\"portfolio\">\r\n");
      out.write("\t\t<div class=\"container-fluid p-0\">\r\n");
      out.write("\t\t\t<div class=\"row no-gutters\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-box\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/fullsize/1.jpg\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/thumbnails/1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-box-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-category text-white-50\">Category</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-name\">Project Name</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-box\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/fullsize/2.jpg\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/thumbnails/2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-box-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-category text-white-50\">Category</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-name\">Project Name</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-box\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/fullsize/3.jpg\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/thumbnails/3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-box-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-category text-white-50\">Category</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-name\">Project Name</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-box\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/fullsize/4.jpg\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/thumbnails/4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-box-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-category text-white-50\">Category</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-name\">Project Name</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-box\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/fullsize/5.jpg\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/thumbnails/5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-box-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-category text-white-50\">Category</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-name\">Project Name</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<a class=\"portfolio-box\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/fullsize/6.jpg\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/portfolio/thumbnails/6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"portfolio-box-caption p-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-category text-white-50\">Category</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project-name\">Project Name</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Call to Action Section -->\r\n");
      out.write("\t<section class=\"page-section bg-dark text-white\">\r\n");
      out.write("\t\t<div class=\"container text-center\">\r\n");
      out.write("\t\t\t<h2 class=\"mb-4\">Free Download at Start Bootstrap!</h2>\r\n");
      out.write("\t\t\t<a class=\"btn btn-light btn-xl\"\r\n");
      out.write("\t\t\t\thref=\"https://startbootstrap.com/themes/creative/\">Download Now!</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Contact Section -->\r\n");
      out.write("\t<section class=\"page-section\" id=\"contact\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mt-0\">Let's Get In Touch!</h2>\r\n");
      out.write("\t\t\t\t\t<hr class=\"divider my-4\">\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted mb-5\">Ready to start your next project\r\n");
      out.write("\t\t\t\t\t\twith us? Give us a call or send us an email and we will get back\r\n");
      out.write("\t\t\t\t\t\tto you as soon as possible!</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ml-auto text-center mb-5 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-phone fa-3x mb-3 text-muted\"></i>\r\n");
      out.write("\t\t\t\t\t<div>+1 (202) 555-0149</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 mr-auto text-center\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-envelope fa-3x mb-3 text-muted\"></i>\r\n");
      out.write("\t\t\t\t\t<!-- Make sure to change the email address in anchor text AND the link below! -->\r\n");
      out.write("\t\t\t\t\t<a class=\"d-block\" href=\"mailto:contact@yourwebsite.com\">contact@yourwebsite.com</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"bg-light py-5\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"small text-center text-muted\">Copyright &copy; 2019\r\n");
      out.write("\t\t\t\t- Start Bootstrap</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\tBootstrap core JavaScript\r\n");
      out.write("\t<script src=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Plugin JavaScript -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for this template -->\r\n");
      out.write("\t<script src=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/creative.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for this template -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
